# Generated by Django 5.2 on 2025-04-14 08:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpenAIFile",
            fields=[
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "checksum",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("file_name", models.CharField(max_length=255)),
                ("path", models.CharField(max_length=255)),
                ("file_key", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        max_length=512,
                        storage=django.core.files.storage.FileSystemStorage(
                            "/subdomain-data/sidecar/openaifiles", base_url="/"
                        ),
                        upload_to="",
                    ),
                ),
            ],
        ),
    ]
