# Generated by Django 5.2 on 2025-04-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openai", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaifile",
            name="checksum",
            field=models.CharField(
                blank=True, max_length=255, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="openaifile",
            name="file_key",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="openaifile",
            name="file_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="openaifile",
            name="path",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
