# Generated by Django 5.2 on 2025-04-14 09:59

import django.core.files.storage
import openai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("openai", "0002_alter_openaifile_checksum_alter_openaifile_file_key_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaifile",
            name="file",
            field=models.FileField(
                max_length=512,
                storage=django.core.files.storage.FileSystemStorage(
                    "/subdomain-data/sidecar/openaifiles", base_url="/"
                ),
                upload_to=openai.models.hashed_upload_to,
            ),
        ),
    ]
