# Generated by Django 5.2 on 2025-04-14 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("openai", "0003_alter_openaifile_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="openaifile",
            old_name="file_name",
            new_name="original_file_name",
        ),
    ]
