# Generated by Django 5.1.2 on 2024-10-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.CharField(max_length=60),
        ),
    ]
