# Generated by Django 5.1.2 on 2024-12-29 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_author_alter_comment_author"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "category"},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="categories",
            new_name="category",
        ),
    ]
