# Generated by Django 5.1.2 on 2024-12-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_category_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="restricted",
            field=models.BooleanField(default=False),
        ),
    ]
