# Generated by Django 5.1.2 on 2024-12-30 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_category_restricted"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="visibility",
            field=models.IntegerField(
                choices=[(1, "Private"), (2, "Public")], default=2
            ),
        ),
    ]
