# Generated by Django 5.1.2 on 2024-12-30 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_post_visibility"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author_type",
            field=models.IntegerField(
                choices=[
                    (0, "Anonymous"),
                    (1, "Student"),
                    (2, "Teacher"),
                    (3, "Staff"),
                ],
                default=0,
            ),
        ),
    ]
