# Generated by Django 5.1.2 on 2025-01-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="visit",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
