# Generated by Django 5.1.2 on 2025-01-11 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0009_visit_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subdomain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment",
                to="blog.post",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="blog.category",
            ),
        ),
        migrations.AlterField(
            model_name="visit",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit",
                to="blog.post",
            ),
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60)),
                ("last_visit", models.DateTimeField(auto_now=True)),
                (
                    "visitor_type",
                    models.IntegerField(
                        choices=[
                            (0, "Anonymous"),
                            (1, "Student"),
                            (2, "Teacher"),
                            (3, "Staff"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "subdomain",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visitor",
                        to="blog.subdomain",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="post_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post",
                to="blog.visitor",
            ),
        ),
    ]
