# Generated by Django 5.1.2 on 2025-01-11 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_alter_visit_post_alter_visit_visitor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visit",
            name="visitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visit_visitor",
                to="blog.visitor",
            ),
        ),
    ]
