# Generated by Django 5.1.2 on 2025-01-11 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0012_alter_visit_visitor"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="comment_author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comment_author",
                to="blog.visitor",
            ),
        ),
    ]
