# Generated by Django 5.1.2 on 2025-01-12 22:03

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0017_alter_comment_body_alter_post_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Comment Body"),
        ),
        migrations.AlterField(
            model_name="post",
            name="body",
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name="Post Body "),
        ),
    ]
