# Generated by Django 5.1.2 on 2025-01-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0018_alter_comment_body_alter_post_body"),
    ]

    operations = [
        migrations.CreateModel(
            name="FilterKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="filter_key",
            field=models.ManyToManyField(to="blog.filterkey"),
        ),
    ]
