# Generated by Django 5.1.2 on 2025-01-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0021_alter_filterkey_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="filterkey",
            name="title",
            field=models.TextField(blank=True, default=""),
        ),
    ]
