# Generated by Django 5.1.2 on 2025-01-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0022_filterkey_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="alias",
            field=models.CharField(blank=True, default="", max_length=120),
        ),
    ]
