# Generated by Django 5.1.2 on 2025-02-01 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0024_filterkey_subdomain"),
    ]

    operations = [
        migrations.AddField(
            model_name="filterkey",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="blog.category",
            ),
        ),
    ]
