# Generated by Django 5.1.2 on 2025-02-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0025_filterkey_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="filter_key",
            field=models.ManyToManyField(related_name="post", to="blog.filterkey"),
        ),
    ]
