# Generated by Django 5.1.2 on 2025-02-05 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0026_alter_post_filter_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="subdomain",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category",
                to="blog.subdomain",
            ),
        ),
        migrations.AlterField(
            model_name="filterkey",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filterkey",
                to="blog.category",
            ),
        ),
    ]
