# Generated by Django 5.1.2 on 2025-02-05 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0027_category_subdomain_alter_filterkey_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filterkey",
            name="subdomain",
        ),
    ]
