# Generated by Django 5.1.2 on 2025-02-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0029_alter_comment_comment_author_alter_post_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
    ]
