# Generated by Django 5.1.2 on 2025-02-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0030_post_resolved"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="filter_key",
            field=models.ManyToManyField(
                blank=True, related_name="post", to="blog.filterkey"
            ),
        ),
    ]
