# Generated by Django 5.1.2 on 2025-03-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0031_alter_post_filter_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="subdomain",
            name="hidden",
            field=models.BooleanField(default=True),
        ),
    ]
