# Generated by Django 5.2 on 2025-04-14 20:39

import django.core.files.storage
import sidecar_openai.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpenAIFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                ("checksum", models.CharField(blank=True, max_length=255)),
                ("original_file_name", models.CharField(blank=True, max_length=255)),
                ("path", models.CharField(blank=True, max_length=255)),
                ("file_id", models.CharField(blank=True, max_length=255)),
                (
                    "file",
                    models.FileField(
                        max_length=512,
                        storage=django.core.files.storage.FileSystemStorage(
                            "/subdomain-data/sidecar/openaifiles", base_url="/"
                        ),
                        upload_to=sidecar_openai.models.hashed_upload_to,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VectorStore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vector_store_id", models.CharField(blank=True, max_length=255)),
                ("name", models.CharField(blank=True, max_length=255)),
                ("files", models.ManyToManyField(to="sidecar_openai.openaifile")),
            ],
        ),
    ]
