# Generated by Django 5.2 on 2025-04-15 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assistant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255)),
                ("instructions", models.TextField(blank=True)),
                ("assistant_id", models.CharField(blank=True, max_length=255)),
                ("json_field", models.JSONField(default={})),
                (
                    "vector_stores",
                    models.ManyToManyField(to="sidecar_openai.vectorstore"),
                ),
            ],
        ),
    ]
