# Generated by Django 5.2 on 2025-04-15 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0002_assistant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="json_field",
            field=models.JSONField(default=dict),
        ),
    ]
