# Generated by Django 5.2 on 2025-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0003_alter_assistant_json_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="json_field",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
