# Generated by Django 5.2 on 2025-04-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0004_alter_assistant_json_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vectorstore",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
