# Generated by Django 5.2 on 2025-04-15 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0005_alter_vectorstore_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="vectorstore",
            name="checksum",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
