# Generated by Django 5.2 on 2025-04-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0006_vectorstore_checksum"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assistant",
            name="vector_stores",
            field=models.ManyToManyField(
                related_name="assistants", to="sidecar_openai.vectorstore"
            ),
        ),
        migrations.AlterField(
            model_name="vectorstore",
            name="files",
            field=models.ManyToManyField(
                related_name="vector_stores", to="sidecar_openai.openaifile"
            ),
        ),
    ]
