# Generated by Django 5.2 on 2025-04-24 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0007_alter_assistant_vector_stores_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assistant",
            name="ntokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="openaifile",
            name="ntokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="vectorstore",
            name="ntokens",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="assistant",
            name="vector_stores",
            field=models.ManyToManyField(to="sidecar_openai.vectorstore"),
        ),
        migrations.AlterField(
            model_name="vectorstore",
            name="files",
            field=models.ManyToManyField(to="sidecar_openai.openaifile"),
        ),
    ]
