# Generated by Django 5.2 on 2025-04-24 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0008_assistant_ntokens_openaifile_ntokens_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assistant",
            name="ntokens",
        ),
        migrations.RemoveField(
            model_name="openaifile",
            name="ntokens",
        ),
        migrations.RemoveField(
            model_name="vectorstore",
            name="ntokens",
        ),
    ]
