# Generated by Django 5.2 on 2025-04-24 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "sidecar_openai",
            "0009_remove_assistant_ntokens_remove_openaifile_ntokens_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="openaifile",
            name="ntokens",
            field=models.IntegerField(default=0),
        ),
    ]
