# Generated by Django 5.2 on 2025-04-24 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0010_openaifile_ntokens"),
    ]

    operations = [
        migrations.AlterField(
            model_name="openaifile",
            name="ntokens",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
