# Generated by Django 5.2 on 2025-04-27 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0011_alter_openaifile_ntokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="Thread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("date", models.DateTimeField(auto_now=True)),
                ("thread_id", models.CharField(blank=True, max_length=255)),
                ("messages", models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
    ]
