# Generated by Django 5.2 on 2025-04-28 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sidecar_openai", "0012_thread"),
    ]

    operations = [
        migrations.AddField(
            model_name="thread",
            name="assistant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="threads",
                to="sidecar_openai.assistant",
            ),
        ),
    ]
