#!/bin/bash
DB_EXISTS=$(psql -U $PGUSER -tAc  "SELECT 1 FROM pg_database WHERE datname='"$PGDATABASE"'")
if [ "$DB_EXISTS" != "1" ]; then
  echo "Database $PGDATABASE does not exist. Creating..."
  createdb -U $PGUSER $PGDATABASE
  echo "Database $PGDATABASE created."
else
  echo "Database $PGDATABASE already exists."
fi
mkdir -p /subdomain-data/${SUBDOMAIN}/media/_versions
echo $PGDATABASE > /subdomain-data/${SUBDOMAIN}/dbname.txt
python manage.py migrate
python manage.py create_superuser
python manage.py loaddata fixtures/initial_data.json
