#!/bin/bash

# Database name

# Check if the database exists
DB_EXISTS=$(psql -U $PGUSER -tAc  "SELECT 1 FROM pg_database WHERE datname='"$PGDATABASE"'")
# Create the database if it does not exist
if [ "$DB_EXISTS" != "1" ]; then
  echo "Database $PGDATABASE does not exist. Creating..."
  createdb -U $DBUSER $PGDATABASE
  echo "Database $PGDATABASE created."
else
  echo "Database $PGDATABASE already exists."
fi
mkdir -p /subdomain-data/${SUBDOMAIN}/media/_versions
echo $PGDATABASE_NAME > "/subdomain_data/${SUBDOMAIN}/dbname.txt"
python manage.py migrate
