kind: PersistentVolume
apiVersion: v1
metadata:
  name: blog-minikube-vol
  labels:
    type: local
spec:
  capacity:
    storage: 10Gi
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv/blog-minikube-vol"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blog-minikube-pvc
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  volumeName: blog-minikube-vol
  resources:
    requests:
      storage: 10Gi
---

kind: PersistentVolume
apiVersion: v1
metadata:
  name: blog-deploystatic-vol
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv/blog-deploystatic-vol"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blog-deploystatic-pvc
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  volumeName: blog-deploystatic-vol
  resources:
    requests:
      storage: 1Gi

---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: blog-subdomain-vol
  labels:
    type: local
spec:
  capacity:
    storage: 20Gi
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/pv/blog-subdomain-vol"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: blog-subdomain-pvc
spec:
  storageClassName: local-hostpath
  accessModes:
    - ReadWriteOnce
  volumeName: blog-subdomain-vol
  resources:
    requests:
      storage: 10Gi
