apiVersion: v1
#  https://jmrobles.medium.com/postgres-connection-pool-on-kubernetes-in-1-minute-80b8020315ef
kind: Pod
metadata:
  labels:
    app: pgbouncer
  name: pgbouncer
spec:
  volumes:
  - name: subdomain-vol
    persistentVolumeClaim:
      claimName: subdomain-pvc
  containers:
  - env:
    - name: TZ
      value: "Europe/StocholEurope/Stocholmm" # Set your desired timezone
    - name: PGHOST
      value: pgbouncer
    - name: PGPASSWORD
      value: 'postgres'
    - name: DB_HOST
      value: db-server
    - name: MAX_CLIENT_CONN
      value: '200'
    - name: DB_PASSWORD
      value: 'postgres'
    - name: DB_USER
      value: 'postgres'
    - name: POOL_MODE
      value: transaction
    - name: SERVER_RESET_QUERY
      value: DISCARD ALL
    image: 'localhost:32000/openta-blog-pgbouncer:latest'
    livenessProbe:
      exec:
       command: ["/subdomain-data/ckpgbouncer"]
      initialDelaySeconds: 10
      periodSeconds: 5
    volumeMounts:
      - mountPath: "/subdomain-data"
        name: subdomain-vol

    #lifecycle:
    #  preStop:
    #    exec:
    #      command:
    #      - /bin/sh
    #      - -c
    #      - killall -INT pgbouncer && sleep 120
    name: pgbouncer
    ports:
    - containerPort: 5432
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - all
