apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sidecar # prefix for  pod names
  labels:
    app: sidecar
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  sidecar
  template:
    metadata:
      labels:
        app: sidecar
    spec:  

      volumes:
      - name: blog-subdomain-vol
        persistentVolumeClaim:
          claimName: blog-subdomain-pvc
      - name: blog-deploystatic-vol
        persistentVolumeClaim:
          claimName: blog-deploystatic-pvc

      containers:
        - name: blog
          image: 'opentaproject/openta-sidecar:latest'
          volumeMounts:
              - mountPath: "/subdomain-data"
                name: blog-subdomain-vol
              - mountPath: "/srv/openta-blog/django/blog/static"
                name: blog-deploystatic-vol
    
          env: 
            - name: TZ
              value: "Europe/Stockholm" # Set your desired timezone
            - name: PGHOST
              value: 'blog-db-server'
            - name: NOT_PGHOST
              value: 'blog-pgbouncer-service'
            - name: DBHOST
              value: 'blog-db-server' # EDIT 
            - name: DEBUG
              value: 'True'
            - name:  SUBDOMAIN
              value: 'sidecar'
            - name: OPENAI_API_KEY
              value: ${OPENAI_API_KEY}
            - name: SUPERUSER_PASSWORD
              value: learning
            - name: PGPASSWORD
              value: postgres
            - name: PGUSER
              value: postgres
            - name: SECRET_KEY
              value: 'abcdefghijklmnopqrst'
            - name: SUPERUSER
              value: super
            - name: PGDATABASE_NAME
              value: 'default'
            - name: LTI_KEY
              value: '889d570f472'
            - name: LTI_SECRET
              value: 'b317476faed2e879'
            - name: PGDATABASE
              value: 'wwwdb'
            - name: HTTP_PROTOCOL
              value: "https"
            - name: HTTP_SERVER_PORT
              value: "443"
          imagePullPolicy: Always
          command: ["/bin/bash","-c"]
          args: 
            - cd django/blog;
              git fetch --all
              git checkout latest;
              ./db_setup ;
              python manage.py makemigrations;
              python manage.py migrate;
              npx @tailwindcss/cli -i static/css/input.css -o static/css/output.css;
              python manage.py collectstatic --no-input;
              /usr/bin/supervisord -c /srv/openta-blog/django/blog/supervisord.conf 
              #python manage.py runserver

        - name: nginx
          image: 'opentaproject/openta-blog-nginx:latest'
          ports: 
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/subdomain-data"
              name: blog-subdomain-vol
            - mountPath: "/deploystatic"
              name: blog-deploystatic-vol





    
---

kind: Service
apiVersion: v1
metadata:
  name: sidecar-service
spec:
  selector:
    app: sidecar
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: 8080
      name: http

