apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: www # prefix for  pod names
  labels:
    app: www
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  www
  template:
    metadata:
      labels:
        app: www
    spec:  

      volumes:
      - name: subdomain-vol
        persistentVolumeClaim:
          claimName: subdomain-pvc
      - name: deploystatic-vol
        persistentVolumeClaim:
          claimName: deploystatic-pvc

      containers:
        - name: blog
          image: 'localhost:32000/openta-blog:latest'
          volumeMounts:
              - mountPath: "/subdomain-data"
                name: subdomain-vol
              - mountPath: "/srv/openta-blog/django/blog/static"
                name: deploystatic-vol
    
          env: 
            - name: TZ
              value: "Europe/Stockholm" # Set your desired timezone
            - name: NOT_PGHOST
              value: 'db-server'
            - name: PGHOST
              value: 'pgbouncer-service'
            - name: DBHOST
              value: 'db-server' # EDIT 
            - name: DEBUG
              value: 'True'
            - name:  SUBDOMAIN
              value: 'www'

            - name: SUPERUSER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openta-secret  # Name of the secret
                  key: SUPERUSER_PASSWORD

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: openta-secret  # Name of the secret
                  key: PGPASSWORD

            - name: PGUSER
              valueFrom:
                secretKeyRef:
                  name: openta-secret  # Name of the secret
                  key: PGUSER

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: openta-secret  # Name of the secret
                  key: SECRET_KEY


            - name: SUPERUSER
              valueFrom:
                secretKeyRef:
                  name: openta-secret  # Name of the secret
                  key: SUPERUSER

            - name: PGDATABASE_NAME
              value: 'default'


            - name: PGDATABASE
              value: 'wwwdb'



            - name: HTTP_PROTOCOL
              value: "https"
            - name: HTTP_SERVER_PORT
              value: "443"
          imagePullPolicy: Always
          command: ["/bin/bash","-c"]
          args: 
            - cd django/blog;
              ./db_setup ;
              python manage.py makemigrations;
              python manage.py migrate;
              python manage.py collectstatic --no-input;
              /usr/bin/supervisord -c /srv/openta-blog/django/blog/supervisord.conf 
              #python manage.py runserver

        - name: nginx
          image: 'localhost:32000/openta-blog-nginx:latest'
          ports: 
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/subdomain-data"
              name: subdomain-vol
            - mountPath: "/deploystatic"
              name: deploystatic-vol





    
---

kind: Service
apiVersion: v1
metadata:
  name: www-service
spec:
  selector:
    app: www
  type: NodePort 
  ports:
    - port: 8000
      targetPort: 8080
      name: http

