apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openta-se-sidecar
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "700m"
spec:
  tls:
    - hosts:
      - 'sidecar.openta.se'   #EDIR
      secretName: openta-se-secret
  ingressClassName: nginx
  rules:
    - host: "sidecar.openta.se" #EDIT THIS
      http:
        paths:
          - pathType: "ImplementationSpecific"
            path: /
            backend:
              service:
                name: sidecar-service
                port:
                  number: 8000

